version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./model:/app/model
      - ./google_api_cache:/app/google_api_cache
    restart: unless-stopped
